result = 1 + 2
print('result =', result)
original_result = result
result = result - 1
print('result =', result)
original_result = result
result = result * 2
print('result =', result)
original_result = result
result = result ** 3
print('result =', result)
original_result = result
result = result + 8
print('result =', result)
original_result = result
result = result % 7
print('result =', result)
original_result = result
result = result // 2
print('result =', result)
original_result = result
#kết quả lần lưởt là 3 2 4 64 72 2 1 